src/AppBundle/Entity/Bunch.php
<?php

namespace AppBundle\Entity;

/**
 * Bunch
 */
class Bunch
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $total;

    /**
     * @var bool
     */
    private $availability;

    /**
     * @var \DateTime
     */
    private $created;

    /**
     * @var \DateTime
     */
    private $updated;

    /**
     * @var array of \Entity
     */
    private $products;

    /**
     * @var boolean
     */
    private $star1;

    /**
     * @var boolean
     */
    private $star2;

    /**
     * @var boolean
     */
    private $star3;

    /**
     * @var enum
     */
    private $ball;

    /**
     * @var array of \Entity
     */
    private $productsSale;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Product
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set total
     *
     * @param string $total
     *
     * @return Product
     */
    public function setTotal($total)
    {
        $this->total = $total;

        return $this;
    }

    /**
     * Get total
     *
     * @return string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Set availability
     *
     * @param boolean $availability
     *
     * @return Product
     */
    public function setAvailability($availability)
    {
        $this->availability = $availability;

        return $this;
    }

    /**
     * Get availability
     *
     * @return bool
     */
    public function getAvailability()
    {
        return $this->availability;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     *
     * @return Product
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     *
     * @return Product
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set Star1
     *
     * @param boolean $star
     *
     * @return ProductStock
     */
    public function setStar1($star)
    {
        $this->star1 = $star;

        return $this;
    }

    /**
     * getStar1
     *
     * @return bool
     */
    public function getStar1()
    {
        return $this->star1;
    }

    /**
     * Set Star2
     *
     * @param boolean $star
     *
     * @return ProductStock
     */
    public function setStar2($star)
    {
        $this->star2 = $star;

        return $this;
    }

    /**
     * getStar2
     *
     * @return bool
     */
    public function getStar2()
    {
        return $this->star2;
    }

    /**
     * Set Star3
     *
     * @param boolean $star
     *
     * @return ProductStock
     */
    public function setStar3($star)
    {
        $this->star3 = $star;

        return $this;
    }

    /**
     * getStar3
     *
     * @return bool
     */
    public function getStar3()
    {
        return $this->star3;
    }

    /**
     * Set Ball
     *
     * @param boolean $ball
     *
     * @return ProductStock
     */
    public function setBall($ball)
    {
        $this->ball = $ball;

        return $this;
    }

    /**
     * getBall
     *
     * @return string
     */
    public function getBall()
    {
        return $this->ball;
    }

    /**
     * setProducts
     *
     * @param $products
     * @return $this
     */
    public function setProducts($products)
    {
        $this->products = $products;

        return $this;
    }

    /**
     * getProducts
     *
     * @return array
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * setProducts
     *
     * @param $products
     * @return $this
     */
    public function setProductsSale($products)
    {
        $this->productsSale = $products;

        return $this;
    }

    /**
     * getProducts
     *
     * @return array
     */
    public function getProductsSale()
    {
        return $this->productsSale;
    }

    /**
     * Get Average Price
     *
     * @return float|int
     */
    public function getAveragePrice()
    {
        $products = $this->getProducts();
        $averagePrice = 0;
        if (count($products)>0) {
            foreach ($products as $item) {
                $averagePrice += $item->getPrice();
            }
            $averagePrice = $averagePrice/count($products);
        }

        return $averagePrice;
    }

    /**
     * Get Average Price BYN
     *
     * @return float|int
     */
    public function getAveragePriceByn()
    {
        $products = $this->getProducts();
        $averagePrice = 0;
        if (count($products)>0) {
            foreach ($products as $item) {
                $averagePrice += $item->getPriceByn();
            }
            $averagePrice = $averagePrice/count($products);
        }

        return $averagePrice;
    }

    /**
     * getLastProduct
     *
     * @return null|\Entity
     */
    public function getLastProduct()
    {
        $products = $this->getProducts();
        $lastProduct = NULL;
        if (count($products)>0) {
            $lastProduct = $products->last();
            $lastDate = $lastProduct->getCreated();
            foreach ($products as $product) {
                if ( $lastDate > $product->getCreated() ) {
                    $lastProduct = $product;
                    $lastDate = $product->getCreated();
                }
            }
        }
        return $lastProduct;
    }

    /**
     * getLastProductPrice
     *
     * @return int|float
     */
    public function getLastProductPrice()
    {
        $product = $this->getLastProduct();
        return (!empty($product) ? $product->getPriceByn() : 0);
    }

    /**
     * getMaxProductByPrice
     *
     * @return mixed|null
     */
    public function getMaxProductByPrice()
    {
        $products = $this->getProducts();
        $returnProductPrice = 0;
        $returnProduct = null;
        if (count($products)>0) {
            foreach ($products as $product) {
                if ($product->getPrice() > $returnProductPrice) {
                    $returnProduct = $product;
                    $returnProductPrice = $product->getPrice();
                }
            }
        }
        return $returnProduct;
    }

    /**
     * getMaxProductByPriceByn
     *
     * @return mixed|null
     */
    public function getMaxProductByPriceByn()
    {
        $products = $this->getProducts();
        $returnProductPrice = 0;
        $returnProduct = null;
        if (count($products)>0) {
            foreach ($products as $product) {
                if ($product->getPriceByn() > $returnProductPrice) {
                    $returnProduct = $product;
                    $returnProductPrice = $product->getPriceByn();
                }
            }
        }
        return $returnProduct;
    }

    /**
     * getMaxProductSaleByPriceByn
     *
     * @return mixed|null
     */
    public function getMaxProductSaleByPriceByn()
    {
        $products = $this->getProductsSale();
        $returnProductPrice = 0;
        $returnProduct = null;
        if (count($products)>0) {
            foreach ($products as $product) {
                if ($product->getPrice() > $returnProductPrice) {
                    $returnProduct = $product;
                    $returnProductPrice = $product->getPrice();
                }
            }
        }
        return $returnProduct;
    }

    /**
     * getMaxPrice
     *
     * @return int
     */
    public function getMaxPrice()
    {
        $product = $this->getMaxProductByPrice();
        return $product ? $product->getPrice() : 0;
    }

    /**
     * getMaxPrice
     *
     * @return int
     */
    public function getMaxSalePrice($rate)
    {
        $product = $this->getMaxProductSaleByPriceByn();
        return $product ? $product->getPrice()/$rate : 0;
    }

    /**
     * getMaxPriceByn
     *
     * @return int
     */
    public function getMaxPriceByn()
    {
        $product = $this->getMaxProductByPriceByn();
        return $product ? $product->getPriceByn() : 0;
    }

    /**
     * getMaxSalePriceByn
     *
     * @return int
     */
    public function getMaxSalePriceByn()
    {
        $product = $this->getMaxProductSaleByPriceByn();
        return $product ? $product->getPrice() : 0;
    }

    /**
     * getMaxProductByPrice
     *
     * @return mixed|null
     */
    public function getMinProductByPrice()
    {
        $products = $this->getProducts();
        $returnProductPrice = 0;
        $returnProduct = null;
        if (count($products)>0) {
            $returnProductPrice = $products[0]->getPrice();
            $returnProduct = $products[0];
            foreach ($products as $product) {
                if ($product->getPrice() < $returnProductPrice) {
                    $returnProduct = $product;
                    $returnProductPrice = $product->getPrice();
                }
            }
        }
        return $returnProduct;
    }

    /**
     * getMinProductByPriceByn
     *
     * @return mixed|null
     */
    public function getMinProductByPriceByn()
    {
        $products = $this->getProducts();
        $returnProductPrice = 0;

src/AppBundle/Resources/views/Export/stock-export.html.twig
{% extends 'export.html.twig' %}

{% block content %}
    {% if items|length > 0 %}
        <table id="product-stock-table">
            <thead>
            <tr>
                <th width="480px">
                    <h3 >Товары</h3>
                </th>
                <th >
                    <h3>Наличие,<br/> шт</h3>
                </th>
                <th >
                    <h3>Резерв,<br/> шт</h3>
                </th>
                <th >
                    <h3>Диапазон цен, руб.</h3>
                </th>
                <th >
                    <h3>Диапазон<br/> цен,$</h3>
                </th>
                <th >
                    <h3>Цена&nbsp;последнего товара, руб.</h3>
                </th>
                <th >
                    <h3>Дата&nbsp;поставки последнего</h3>
                </th>
            </tr>
            </thead>
            <tbody>
            {% for item in items %}
                {% if item.0 is defined %}
                    {% set bunch = item.0 %}
                    {% if item.last_date is defined %}{% set last_date = item.last_date %}{% else %}{% set last_date = bunch.lastDate %}{% endif %}
                {% else %}
                    {% set bunch = item %}
                {% endif %}
                <tr  data-category="{{ bunch.id }}">
                    <td class="title-tr txt-left td-border-right {% if bunch.lastProduct is defined and bunch.lastProduct.dateDiff|date("%m") > 0 %}title-right-offset{% endif %}">
                        <a href="#" >{{ bunch.title }}</a>
                    </td>
                    <td>
                        <a href="#">{{ bunch.total }}</a>
                    </td>
                    <td>
                        <a href="#">0</a>
                    </td>
                    <td >
                        <a href="#">{% if bunch.maxPriceByn != bunch.minPriceByn %}{{ bunch.minPriceByn|number_format(2, ',', '') }}-{{ bunch.maxPriceByn|number_format(2, ',', '') }}{% else %}{{ bunch.minPriceByn|number_format(2, ',', '') }}{% endif %}</a>
                    </td>
                    <td>
                        <a href="#">{% if bunch.maxPrice != bunch.minPrice %}{{ bunch.minPrice|number_format(2, ',', '') }}-{{ bunch.maxPrice|number_format(2, ',', '') }}{% else %}{{ bunch.minPrice|number_format(2, ',', '') }}{% endif %}</a>
                    </td>
                    <td>
                        <a href="#">{{ bunch.lastProductPrice|number_format(2, ',', '') }}</a>
                    </td>
                    <td>
                        <a href="#">{% if bunch.lastProduct is not null %}{{ bunch.lastProduct.created|date("d-m-Y") }}{% endif %}</a>
                    </td>
                </tr>
                <tr data-category="{{ bunch.id }}" >
                    <td colspan="8">
                        <table>
                            <tbody>
                            {% for product in bunch.getProducts() %}
                                <tr>
                                    <td>

                                        {{ product.title }}
                                    </td>
                                    <td width="88px">
                                        <input type="text"  name="qty" value="{{ product.qty }}" />
                                    </td>
                                    <td width="79px">
                                        <a href="#">0</a>
                                    </td>
                                    <td  width="108px">
                                        <a href="#">{{ product.priceByn|number_format(2, ',', '') }}</a>
                                    </td>
                                    <td width="101px">
                                        <a href="#">{{ product.price|number_format(2, ',', '') }}</a>
                                    </td>
                                    <td width="148px">
                                        <a href="#">{{ product.priceByn|number_format(2, ',', '') }}</a>
                                    </td>
                                    <td width="141px">
                                        <a href="#">{{ product.created|date("d-m-Y") }}</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p ><span >Нет данных</span></p>
    {% endif %}
{% endblock %}